modLoader="javafml"
loaderVersion="[47,)"
license="MIT"

[[mods]]
modId="betterf1"
version="1.0.0"
displayName="Better F1"
authors="Akoto090"
description='''A Forge 1.20.1 port of the BetterF1 mod.'''

[[dependencies.betterf1]]
modId="forge"
mandatory=true
versionRange="[47,)"
ordering="NONE"
side="CLIENT"

[[dependencies.betterf1]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,1.21)"
ordering="NONE"
side="CLIENT"